api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml

log:
  level: INFO

accessLog: {}

certificatesResolvers:
  letsencrypt:
    acme:
      email: hammoudiwissem81@email.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

